name: Destroy DigitalOcean Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm infrastructure deletion'
        required: true
        type: string

concurrency:
  group: k8s-deployment-${{ github.ref }}
  cancel-in-progress: false

env:
  TF_ROOT: terraform

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    environment: 
      name: destruction
    if: github.event.inputs.confirm_destroy == 'DESTROY'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.0
    
    - name: Set Kubernetes Version (for state consistency)
      run: |
        cd $TF_ROOT
        # Install doctl to get available versions
        curl -sL https://github.com/digitalocean/doctl/releases/download/v1.104.0/doctl-1.104.0-linux-amd64.tar.gz | tar -xzv
        sudo mv doctl /usr/local/bin
        doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
        # Get available versions and use stored or find fallback
        AVAILABLE_VERSIONS=$(doctl kubernetes options versions -o json | jq -r '.[].slug')
        
        if [ -n "${{ vars.KUBECONFIG_B64 }}" ]; then
          echo "📦 Using kubeconfig to determine cluster version..."
          mkdir -p terraform
          echo "${{ vars.KUBECONFIG_B64 }}" | base64 -d > terraform/kubeconfig
          # Try to get cluster info, but don't fail if cluster is already gone
          CLUSTER_VERSION=$(kubectl version --short 2>/dev/null | grep "Server Version" | cut -d' ' -f3 | sed 's/v//' || echo "")
          if [ -n "$CLUSTER_VERSION" ]; then
            # Find matching DO version
            SELECTED_VERSION=$(echo "$AVAILABLE_VERSIONS" | grep "$CLUSTER_VERSION" | head -n 1)
          fi
        fi
        
        if [ -z "$SELECTED_VERSION" ]; then
          # Fallback to default from variables.tf
          DEFAULT_VERSION=$(grep 'default.*=' terraform/variables.tf | grep -o '"[^"]*"' | tr -d '"')
          echo "🔄 Using default version: $DEFAULT_VERSION"
          SELECTED_VERSION=$DEFAULT_VERSION
        fi
        
        echo "TF_VAR_k8s_version=$SELECTED_VERSION" >> $GITHUB_ENV
        echo "📌 Using Kubernetes version: $SELECTED_VERSION"
    
    - name: Terraform Init
      run: |
        cd $TF_ROOT
        terraform init
      env:
        TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Import Cluster if Needed
      run: |
        cd $TF_ROOT
        echo "🔍 Checking Terraform state and cluster existence..."
        
        # Check if cluster exists in Terraform state
        if terraform state list | grep -q "digitalocean_kubernetes_cluster.main"; then
          echo "✅ Cluster found in Terraform state"
        else
          echo "⚠️ Cluster not found in Terraform state, checking DigitalOcean..."
          
          # Check if cluster exists in DigitalOcean
          CLUSTER_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" \
            "https://api.digitalocean.com/v2/kubernetes/clusters" | \
            jq -r '.kubernetes_clusters[] | select(.name=="gitlab-cluster") | .id')
          
          if [ -n "$CLUSTER_ID" ] && [ "$CLUSTER_ID" != "null" ]; then
            echo "📥 Found existing cluster in DigitalOcean: $CLUSTER_ID"
            echo "🔄 Importing cluster into Terraform state..."
            terraform import digitalocean_kubernetes_cluster.main $CLUSTER_ID
            echo "✅ Import completed"
          else
            echo "ℹ️ No cluster named 'gitlab-cluster' found in DigitalOcean"
            echo "✅ Nothing to destroy"
          fi
        fi
      env:
        TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Show Infrastructure to be Destroyed
      run: |
        cd $TF_ROOT
        echo "🔍 Infrastructure that will be DESTROYED:"
        echo "=========================================="
        terraform plan -destroy -no-color || echo "ℹ️ No infrastructure found to destroy"
        echo "=========================================="
      env:
        TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Destroy Infrastructure
      run: |
        cd $TF_ROOT
        echo "💥 DESTROYING infrastructure..."
        
        # Check if there's anything to destroy
        if terraform state list | grep -q "digitalocean_kubernetes_cluster.main"; then
          terraform destroy -auto-approve
          echo "✅ Infrastructure destroyed successfully"
        else
          echo "ℹ️ No infrastructure found in Terraform state"
          echo "🔍 Checking for orphaned resources in DigitalOcean..."
          
          # Try to destroy cluster directly via API if it exists
          CLUSTER_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" \
            "https://api.digitalocean.com/v2/kubernetes/clusters" | \
            jq -r '.kubernetes_clusters[] | select(.name=="gitlab-cluster") | .id')
          
          if [ -n "$CLUSTER_ID" ] && [ "$CLUSTER_ID" != "null" ]; then
            echo "🗑️ Found orphaned cluster, deleting via API..."
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" \
              "https://api.digitalocean.com/v2/kubernetes/clusters/$CLUSTER_ID"
            echo "✅ Orphaned cluster deleted"
          else
            echo "✅ No orphaned resources found"
          fi
        fi
      env:
        TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Clean up Repository Variables
      run: |
        echo "🧹 Cleaning up stored kubeconfig..."
        curl -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${{ github.api_url }}/repos/${{ github.repository }}/actions/variables/KUBECONFIG_B64" || echo "Variable already deleted or doesn't exist"
        echo "✅ Cleanup completed"

  confirmation_failed:
    name: Destroy Confirmation Failed
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy != 'DESTROY'
    
    steps:
    - name: Show Confirmation Error
      run: |
        echo "❌ DESTROY CANCELLED"
        echo "You entered: '${{ github.event.inputs.confirm_destroy }}'"
        echo "Required: 'DESTROY'"
        echo ""
        echo "To destroy infrastructure, you must type exactly: DESTROY"
        exit 1